package com.yepit.mapp.crp.domain.system;

import java.io.Serializable;

public class Area implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.parent_area_id
     *
     * @mbggenerated
     */
    private Integer parentAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.area_name
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.area_level
     *
     * @mbggenerated
     */
    private Integer areaLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_area
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.area_id
     *
     * @return the value of s_area.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.area_id
     *
     * @param areaId the value for s_area.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.parent_area_id
     *
     * @return the value of s_area.parent_area_id
     *
     * @mbggenerated
     */
    public Integer getParentAreaId() {
        return parentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.parent_area_id
     *
     * @param parentAreaId the value for s_area.parent_area_id
     *
     * @mbggenerated
     */
    public void setParentAreaId(Integer parentAreaId) {
        this.parentAreaId = parentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.area_name
     *
     * @return the value of s_area.area_name
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.area_name
     *
     * @param areaName the value for s_area.area_name
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.area_level
     *
     * @return the value of s_area.area_level
     *
     * @mbggenerated
     */
    public Integer getAreaLevel() {
        return areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.area_level
     *
     * @param areaLevel the value for s_area.area_level
     *
     * @mbggenerated
     */
    public void setAreaLevel(Integer areaLevel) {
        this.areaLevel = areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.area_code
     *
     * @return the value of s_area.area_code
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.area_code
     *
     * @param areaCode the value for s_area.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_area
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Area other = (Area) that;
        return (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
            && (this.getParentAreaId() == null ? other.getParentAreaId() == null : this.getParentAreaId().equals(other.getParentAreaId()))
            && (this.getAreaName() == null ? other.getAreaName() == null : this.getAreaName().equals(other.getAreaName()))
            && (this.getAreaLevel() == null ? other.getAreaLevel() == null : this.getAreaLevel().equals(other.getAreaLevel()))
            && (this.getAreaCode() == null ? other.getAreaCode() == null : this.getAreaCode().equals(other.getAreaCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_area
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getParentAreaId() == null) ? 0 : getParentAreaId().hashCode());
        result = prime * result + ((getAreaName() == null) ? 0 : getAreaName().hashCode());
        result = prime * result + ((getAreaLevel() == null) ? 0 : getAreaLevel().hashCode());
        result = prime * result + ((getAreaCode() == null) ? 0 : getAreaCode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_area
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", areaId=").append(areaId);
        sb.append(", parentAreaId=").append(parentAreaId);
        sb.append(", areaName=").append(areaName);
        sb.append(", areaLevel=").append(areaLevel);
        sb.append(", areaCode=").append(areaCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}