package com.yepit.flow.bo;

import com.yepit.flow.bo.BusMilestone;
import com.yepit.flow.dto.BusMilestoneDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface BusMilestoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_milestone
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_milestone
     *
     * @mbg.generated
     */
    int insert(BusMilestone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_milestone
     *
     * @mbg.generated
     */
    BusMilestone selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_milestone
     *
     * @mbg.generated
     */
    List<BusMilestone> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_milestone
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusMilestone record);

    List<BusMilestone> selectByCond(@Param("pa")Map<String,Object> pa);

    List<BusMilestone> listMilestoneByBusId(@Param("busId") Long busId);

    List<BusMilestone> queryMileStoneByBusIdAndTaskDefId(@Param("busId")Long busId, @Param("taskDefId")String taskDefId);

    List<BusMilestone> pageSearchMileStone(@Param("busId")Long busId, @Param("taskId")String taskId);

    List<BusMilestoneDTO> pageSearchTaskByUserId(@Param("userId") Long userId);

    List<BusMilestone> listTaskByUserId(@Param("userId") Long userId);

    List<BusMilestone> getUserHisTaskByUserId(@Param("assignUser") Long assignUser,@Param("status")String status);

    List<BusMilestoneDTO> pageSearchUserHisTaskByUserId(@Param("assignUser") Long assignUser,@Param("status")String status);

    Long myTaskCount(@Param("assignUser")Long assignUser, @Param("status")String status);
}