package com.yepit.flow.bo;

import java.io.Serializable;
import java.util.Date;

public class BusMilestone implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.bus_id
     *
     * @mbg.generated
     */
    private Long busId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.task_def_id
     *
     * @mbg.generated
     */
    private String taskDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.current_task
     *
     * @mbg.generated
     */
    private String currentTask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.assigement_user
     *
     * @mbg.generated
     */
    private Long assigementUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.assigement_user_name
     *
     * @mbg.generated
     */
    private String assigementUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.done_result
     *
     * @mbg.generated
     */
    private String doneResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.done_remark
     *
     * @mbg.generated
     */
    private String doneRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_milestone.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bus_milestone
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.id
     *
     * @return the value of bus_milestone.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.id
     *
     * @param id the value for bus_milestone.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.bus_id
     *
     * @return the value of bus_milestone.bus_id
     *
     * @mbg.generated
     */
    public Long getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.bus_id
     *
     * @param busId the value for bus_milestone.bus_id
     *
     * @mbg.generated
     */
    public void setBusId(Long busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.task_id
     *
     * @return the value of bus_milestone.task_id
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.task_id
     *
     * @param taskId the value for bus_milestone.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.task_def_id
     *
     * @return the value of bus_milestone.task_def_id
     *
     * @mbg.generated
     */
    public String getTaskDefId() {
        return taskDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.task_def_id
     *
     * @param taskDefId the value for bus_milestone.task_def_id
     *
     * @mbg.generated
     */
    public void setTaskDefId(String taskDefId) {
        this.taskDefId = taskDefId == null ? null : taskDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.current_task
     *
     * @return the value of bus_milestone.current_task
     *
     * @mbg.generated
     */
    public String getCurrentTask() {
        return currentTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.current_task
     *
     * @param currentTask the value for bus_milestone.current_task
     *
     * @mbg.generated
     */
    public void setCurrentTask(String currentTask) {
        this.currentTask = currentTask == null ? null : currentTask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.assigement_user
     *
     * @return the value of bus_milestone.assigement_user
     *
     * @mbg.generated
     */
    public Long getAssigementUser() {
        return assigementUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.assigement_user
     *
     * @param assigementUser the value for bus_milestone.assigement_user
     *
     * @mbg.generated
     */
    public void setAssigementUser(Long assigementUser) {
        this.assigementUser = assigementUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.assigement_user_name
     *
     * @return the value of bus_milestone.assigement_user_name
     *
     * @mbg.generated
     */
    public String getAssigementUserName() {
        return assigementUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.assigement_user_name
     *
     * @param assigementUserName the value for bus_milestone.assigement_user_name
     *
     * @mbg.generated
     */
    public void setAssigementUserName(String assigementUserName) {
        this.assigementUserName = assigementUserName == null ? null : assigementUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.done_result
     *
     * @return the value of bus_milestone.done_result
     *
     * @mbg.generated
     */
    public String getDoneResult() {
        return doneResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.done_result
     *
     * @param doneResult the value for bus_milestone.done_result
     *
     * @mbg.generated
     */
    public void setDoneResult(String doneResult) {
        this.doneResult = doneResult == null ? null : doneResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.done_remark
     *
     * @return the value of bus_milestone.done_remark
     *
     * @mbg.generated
     */
    public String getDoneRemark() {
        return doneRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.done_remark
     *
     * @param doneRemark the value for bus_milestone.done_remark
     *
     * @mbg.generated
     */
    public void setDoneRemark(String doneRemark) {
        this.doneRemark = doneRemark == null ? null : doneRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.start_date
     *
     * @return the value of bus_milestone.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.start_date
     *
     * @param startDate the value for bus_milestone.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.end_date
     *
     * @return the value of bus_milestone.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.end_date
     *
     * @param endDate the value for bus_milestone.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_milestone.status
     *
     * @return the value of bus_milestone.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_milestone.status
     *
     * @param status the value for bus_milestone.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_milestone
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", busId=").append(busId);
        sb.append(", taskId=").append(taskId);
        sb.append(", taskDefId=").append(taskDefId);
        sb.append(", currentTask=").append(currentTask);
        sb.append(", assigementUser=").append(assigementUser);
        sb.append(", assigementUserName=").append(assigementUserName);
        sb.append(", doneResult=").append(doneResult);
        sb.append(", doneRemark=").append(doneRemark);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}