package com.yepit.flow.bo;

import com.yepit.flow.dto.TaskInfoDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long busId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_task
     *
     * @mbg.generated
     */
    int insert(BusTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_task
     *
     * @mbg.generated
     */
    BusTask selectByPrimaryKey(Long busId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_task
     *
     * @mbg.generated
     */
    List<BusTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusTask record);

    /**
     * 分页查询用户参与过的任务
     * @param assignUser
     * @param status
     * @return
     */
    public List<TaskInfoDTO> pageSearchUserHisTaskByUserId(@Param("assignUser") Long assignUser, @Param("status")String status);
}