package com.yepit.flow.bo;

import java.io.Serializable;

public class BusTaskConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task_config.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task_config.up_id
     *
     * @mbg.generated
     */
    private Long upId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task_config.task_name
     *
     * @mbg.generated
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task_config.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task_config.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bus_task_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task_config.id
     *
     * @return the value of bus_task_config.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task_config.id
     *
     * @param id the value for bus_task_config.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task_config.up_id
     *
     * @return the value of bus_task_config.up_id
     *
     * @mbg.generated
     */
    public Long getUpId() {
        return upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task_config.up_id
     *
     * @param upId the value for bus_task_config.up_id
     *
     * @mbg.generated
     */
    public void setUpId(Long upId) {
        this.upId = upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task_config.task_name
     *
     * @return the value of bus_task_config.task_name
     *
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task_config.task_name
     *
     * @param taskName the value for bus_task_config.task_name
     *
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task_config.task_id
     *
     * @return the value of bus_task_config.task_id
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task_config.task_id
     *
     * @param taskId the value for bus_task_config.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task_config.state
     *
     * @return the value of bus_task_config.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task_config.state
     *
     * @param state the value for bus_task_config.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_task_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", upId=").append(upId);
        sb.append(", taskName=").append(taskName);
        sb.append(", taskId=").append(taskId);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}