package com.yepit.flow.bo;

import java.io.Serializable;
import java.util.Date;

public class BusTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task.bus_id
     *
     * @mbg.generated
     */
    private Long busId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task.bus_name
     *
     * @mbg.generated
     */
    private String busName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task.create_user_id
     *
     * @mbg.generated
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task.create_user_name
     *
     * @mbg.generated
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task.customer_Name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task.customer_Mobile
     *
     * @mbg.generated
     */
    private String customerMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task.flow_id
     *
     * @mbg.generated
     */
    private String flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_task.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bus_task
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task.bus_id
     *
     * @return the value of bus_task.bus_id
     *
     * @mbg.generated
     */
    public Long getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task.bus_id
     *
     * @param busId the value for bus_task.bus_id
     *
     * @mbg.generated
     */
    public void setBusId(Long busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task.bus_name
     *
     * @return the value of bus_task.bus_name
     *
     * @mbg.generated
     */
    public String getBusName() {
        return busName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task.bus_name
     *
     * @param busName the value for bus_task.bus_name
     *
     * @mbg.generated
     */
    public void setBusName(String busName) {
        this.busName = busName == null ? null : busName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task.create_user_id
     *
     * @return the value of bus_task.create_user_id
     *
     * @mbg.generated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task.create_user_id
     *
     * @param createUserId the value for bus_task.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task.create_user_name
     *
     * @return the value of bus_task.create_user_name
     *
     * @mbg.generated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task.create_user_name
     *
     * @param createUserName the value for bus_task.create_user_name
     *
     * @mbg.generated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task.customer_Name
     *
     * @return the value of bus_task.customer_Name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task.customer_Name
     *
     * @param customerName the value for bus_task.customer_Name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task.customer_Mobile
     *
     * @return the value of bus_task.customer_Mobile
     *
     * @mbg.generated
     */
    public String getCustomerMobile() {
        return customerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task.customer_Mobile
     *
     * @param customerMobile the value for bus_task.customer_Mobile
     *
     * @mbg.generated
     */
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile == null ? null : customerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task.create_date
     *
     * @return the value of bus_task.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task.create_date
     *
     * @param createDate the value for bus_task.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task.flow_id
     *
     * @return the value of bus_task.flow_id
     *
     * @mbg.generated
     */
    public String getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task.flow_id
     *
     * @param flowId the value for bus_task.flow_id
     *
     * @mbg.generated
     */
    public void setFlowId(String flowId) {
        this.flowId = flowId == null ? null : flowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task.end_date
     *
     * @return the value of bus_task.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task.end_date
     *
     * @param endDate the value for bus_task.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_task.status
     *
     * @return the value of bus_task.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_task.status
     *
     * @param status the value for bus_task.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_task
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", busId=").append(busId);
        sb.append(", busName=").append(busName);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createUserName=").append(createUserName);
        sb.append(", customerName=").append(customerName);
        sb.append(", customerMobile=").append(customerMobile);
        sb.append(", createDate=").append(createDate);
        sb.append(", flowId=").append(flowId);
        sb.append(", endDate=").append(endDate);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}