spring:
  profiles:
    active: dev
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
eureka:
  server:
    use-read-only-response-cache: false
    response-cache-auto-expiration-in-seconds: 10
    response-cache-update-interval-ms: 3000
    eviction-interval-timer-in-ms: 3000
    enable-self-preservation: false
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'