spring:
  application:
    name: car-gateway
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      # Threshold after which files will be written to disk.
      file-size-threshold: 0
      # Intermediate location of uploaded files.
      location:
      # Max file size.
      max-file-size: 20MB
      # Max request size.
      max-request-size: 100MB

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
