server:
  port: 9088

zuul:
  routes:
    mapp-mgt:
      path: /mapp-mgt/**
      url: http://47.99.182.26:9080/
    mapp-flow:
      path: /mapp-flow/**
      url: http://47.99.182.26:8383/

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:47.99.182.26}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
